default:
  tags:
    - shell

variables:
  ANSIBLE_KEY: $ssh_key

stages:         
  - deploy
  - deploy_exporters
  - deploy_beats
  - alert_update


##
# Connnection
.ansible_step:
  before_script:
    - rm -rf ~/.ssh
    - mkdir ~/.ssh
    - echo "${ANSIBLE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

deploy-monitoring:      
  stage: deploy
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/monitoring ./Ansible/monitoring.yml
  when: manual
  needs: []

deploy-victoria:      
  stage: deploy
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/monitoring ./Ansible/victoria.yml
  when: manual
  needs: []

Node_Exporter:      
  stage: deploy_exporters
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/Node_Exporter ./Ansible/NodeExporter.yml
  when: manual
  needs: []

BlackBox_Exporter:      
  stage: deploy_exporters
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/blackboxExporter.yml
  when: manual
  needs: []

Mysql_Exporter:      
  stage: deploy_exporters
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/mysqlexporter.yml
  when: manual
  needs: []

deploy-app:      
  stage: deploy
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/wordpress.yml
  when: manual
  needs: []

alert-update:      
  stage: alert_update
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook -i ./Ansible/Inventory/monitoring ./Ansible/alert.yml
  when: manual
  needs: []

deploy_metricbeat:      
  stage: deploy_beats
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/metricbeat.yml
  when: manual
  needs: []

deploy_filebeat:      
  stage: deploy_beats
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/filebeat.yml
  when: manual
  needs: []

deploy_vector:      
  stage: deploy
  extends: .ansible_step
  script:
    - echo "Started deploy pipeline! 🚀"
    - ansible-playbook  -i ./Ansible/Inventory/app ./Ansible/vector.yml
  when: manual
  needs: []
