---
- name: Install mariadb
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - mariadb-server
    - mariadb-client

- name: Copy 50-server.cnf
  template:
    src: "mariadb/50-server.cnf.j2"
    dest: "/etc/mysql/mariadb.conf.d/50-server.cnf"
    owner: root
    group: root
    mode: 0644

- name: Check status
  shell: "systemctl is-active mariadb.service"
  register: mariadb_status
  failed_when: mariadb_status.rc < 0

- name: Restart mariadb
  service:
    name: mysql
    state: restarted
  when: mariadb_status.stdout == "active"

- name: Enabled mariadb
  service:
    name: mysql
    enabled: yes
    state: started
  when: mariadb_status.stdout != "active"
